import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import dotenv from "dotenv";

dotenv.config();

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for the application
export const metadata: Metadata = {
  title: "TrafficWatch",
  description: "Generated by create next app",
  // Consider adding more metadata here for SEO
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
                {children}
      </body>
    </html>
  );
}
