import type { Metadata } from "next";

export const metadata = {
    title: "TrafficWatch",
    description: "Generated by create next app",
    // Tambahkan metadata lainnya jika diperlukan
    keywords: "Traffic, Monitoring, Banda Aceh, Real-Time",
    author: "Your Name",
  };
  